server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/start-lover?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  file:
    path: ~/logs

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: swagger
    disable-swagger-default-url: true
  packages-to-scan: "com.lover.controllers"